### PR TITLE
[cmake] Added options to select/disable dependencies of iDynTree

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology-playground/iDynTree-superbuild/issues/1 . 
With this options, you should be able to build iDynTree without ICUB, and with YARP compile without ACE (just GSL that is strictly necessary by the part of iDynTree that uses YARP).

### CODE REVIEW

**Comment by kjyv** [comment]
Ok, nice. Something is wrong though with the way the KDL check is done in libraries/iDynTree/bindings/CMakeLists.txt:17. I can build fine if I don't enable e.g. the python binding. With it enabled (and KDL), I get "Impossible generated bindings if KDL is not enabled". (Should be "impossible to generate" btw.).
It seems the higher level option IDYNTREE_SUPERBUILD_USES_KDL does not result in also setting IDYNTREE_USES_KDL before this point and it is hence always false at this point?

**Comment by kjyv** [comment]
Ah, yeah, copy and paste error I guess. In cmake/BuildiDynTree.cmake:50, it should be IDYNTREE_SUPERBUILD_USES_KDL not IDYNTREE_SUPERBUILD_USES_MATLAB.
However, iDyntree now tries to build with Yarp again because of model_io/symoro/CMakeLists.txt:7

**Comment by kjyv** [comment]
So to follow up on this, I would suggest adding "and IDYNTREE_USES_YARP" to the condition to include the symoro subdirectory in model_io/CMakeList.txt. It fixes all problems for me.

**Comment by traversaro** [comment]
I pushed a bunch of fixes in iDynTree, including also that one. I also migrated the Travis infrastructure to Trusty, and I am waiting if the latest fixes have resolved all the issues.

**Comment by kjyv** [comment]
I see, so YARP wasn't necessary there. Even better :)

**Comment by kjyv** [comment]
bump. this works fine in practice, but the failing tests seem weird

**Comment by traversaro** [comment]
Apparently this was done independently in https://github.com/robotology/idyntree-superbuild/commit/35996c01a4f376e495e6923bb4ae79978fe13854 , closing until there was some other issue that needed to be fixed by this PR.

**Pull request closed without merging**
